# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_gen/pkcs11.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15grpc_gen/pkcs11.proto\"]\n\x08SignInit\x12\x16\n\x0esession_handle\x18\x01 \x01(\r\x12%\n\tmechanism\x18\x02 \x01(\x0e\x32\x12.CK_MECHANISM_TYPE\x12\x12\n\nkey_handle\x18\x03 \x01(\r\"0\n\x10SignInitResponse\x12\x1c\n\x0creturn_value\x18\x01 \x01(\x0e\x32\x06.CK_RV\",\n\x04Sign\x12\x16\n\x0esession_handle\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"R\n\x0cSignResponse\x12\x1c\n\x0creturn_value\x18\x01 \x01(\x0e\x32\x06.CK_RV\x12\x16\n\tsignature\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\x0c\n\n_signature*R\n\x05\x43K_RV\x12\n\n\x06\x43KR_OK\x10\x00\x12\x19\n\x14\x43KR_OPERATION_ACTIVE\x10\x90\x01\x12\"\n\x1d\x43KR_OPERATION_NOT_INITIALIZED\x10\x91\x01*<\n\x11\x43K_MECHANISM_TYPE\x12\x0c\n\x08\x43KM_NULL\x10\x00\x12\x19\n\x14\x43KM_CKM_ECDSA_SHA256\x10\xc4 2X\n\x06PKCS11\x12,\n\nC_SignInit\x12\t.SignInit\x1a\x11.SignInitResponse\"\x00\x12 \n\x06\x43_Sign\x12\x05.Sign\x1a\r.SignResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_gen.pkcs11_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CK_RV']._serialized_start=300
  _globals['_CK_RV']._serialized_end=382
  _globals['_CK_MECHANISM_TYPE']._serialized_start=384
  _globals['_CK_MECHANISM_TYPE']._serialized_end=444
  _globals['_SIGNINIT']._serialized_start=25
  _globals['_SIGNINIT']._serialized_end=118
  _globals['_SIGNINITRESPONSE']._serialized_start=120
  _globals['_SIGNINITRESPONSE']._serialized_end=168
  _globals['_SIGN']._serialized_start=170
  _globals['_SIGN']._serialized_end=214
  _globals['_SIGNRESPONSE']._serialized_start=216
  _globals['_SIGNRESPONSE']._serialized_end=298
  _globals['_PKCS11']._serialized_start=446
  _globals['_PKCS11']._serialized_end=534
# @@protoc_insertion_point(module_scope)
